import { Cormorant } from "next/font/google";
import { cn } from "@/lib/utils";
import "./globals.css";
import Navbar from "@/components/Navigation/Navbar";
//import Navbar from "@/components/Navbar/Navbar";
//import NavbarClient from "@/components/Navbar/NavbarClient";
import Footer from "@/components/Footer/Footer";

export const cormorant = Cormorant({
	subsets: ["latin"],
	variable: "--font-fancy",
	display: "swap",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={cn(
					"min-h-screen bg-background font-sans antialiased",
					cormorant.variable
				)}
			>
				{/* 
				<NavbarClient>
					<Navbar />
				</NavbarClient>*/}
				<Navbar />
				{children}
				<Footer />
			</body>
		</html>
	);
}
